---
- hosts: localhost
  tasks:
    - name: Ensure a SSH key is present
      community.digitalocean.digital_ocean:
        state: present
        command: ssh
        name: sothy
        api_token: "ww"
      register: my_ssh
    - debug:
        msg: "ID is {{ my_ssh}}"
    - debug:
        msg: "ssh_key is {{ my_ssh.ssh_key}}"
    - debug:
        msg: "ID is {{ my_ssh.ssh_key.id }}"
    - debug:
        msg: "{{ my_ssh.ssh_key.public_key }}"
    - name: Create a new Droplet
      community.digitalocean.digital_ocean_droplet:
        state: present
        ssh_keys: ['{{ my_ssh.ssh_key.id }}']
        name: "{{ item }}"
        unique_name: "true"
        oauth_token: "ww"
        size: s-2vcpu-4gb
        region: sgp1
        image: ubuntu-24-04-x64
        #image: docker-20-04
        wait_timeout: 500
      loop:
        - nginx-01
        - nginx-02
        - nginx-03
