- hosts: localhost
  gather_facts: true
  vars: 
    test: "hello"
  tasks:
    - name: welcome message 
      debug:
        msg: "welcome to ansible session"
    - name: print message 
      debug:
        msg: "{{ ansible_os_family }}"
    
